### ISSUE TITLE
Multi-view ReFit

### ISSUE THREAD

**Issue by HeroBaoYX** [yufu-wang/ReFit#3]
Thank you for the excellent job you have done. Can you provide more code details about Multi-view ReFit, thank you very much.

**Comment by yufu-wang** [comment]
Thanks for reaching out! Please take a look at this script as well as the model it uses:
https://github.com/yufu-wang/ReFit/blob/main/scripts/eval_mv.py
We cannot release the annotation for h36m at this point, but the multiview fitting code should work when the input's batch dimention is the number of views. We are working to release more details about this. Thank you for your patient!

**Comment by HeroBaoYX** [comment]
> Thanks for reaching out! Please take a look at this script as well as the model it uses: https://github.com/yufu-wang/ReFit/blob/main/scripts/eval_mv.py We cannot release the annotation for h36m at this point, but the multiview fitting code should work when the input's batch dimention is the number of views. We are working to release more details about this. Thank you for your patient!

Thanks for your answer. I will attempt the solution you provided.
